# Typically created via:
# kubectl create secret docker-registry regcred \
#   --docker-server=myregistry.example.com \
#   --docker-username=user --docker-password=pass --docker-email=user@example.com
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHt9fQ==
